server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

#eureka:
#  instance:
#    prefer-ip-address: true
#    status-page-url-path: /swagger-ui.html
#  client:
#    service-url:
#      defaultZone: http://admin:pwd@localhost:8761/eureka/

spring:
  application:
    name: spring-camunda
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/db_camunda?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

camunda.bpm:
  # 是否启用自动部署
  auto-deployment-enabled: false
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks
  database:
    type: mysql
    schema-update: true


# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.asarao.model
  global-config:
    db-config:
      id-type: ID_WORKER
      field-strategy: NOT_EMPTY
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# logging
logging:
  level:
    com.asarao: debug
